config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root 'courses#index'

  resources :users, only: [:show, :index]

  resources :courses do
    resources :lessons
  end

  resources :enrollments, only: [:new, :create, :index, :destroy, :show]

  resources :questions, only: [:index, :create, :new, :edit, :destroy, :update] do
    resources :answers
  end

  resources :texts, only: [:create]

  namespace :api do
    namespace :v1 do
      resources :questions, only: [:destroy]
      resources :enrollments, only: [:destroy]
      resources :lessons, only: [:update]
      resources :courses, only: [:index]
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :lesson
  has_many :answers

  validates :question, presence: true
  validates :lesson_id, presence: true
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  def destroy
    @question = Question.find(params[:id])
    if @question.destroy
      flash[:notice] = "We got you. Your question will no longer be asked."
      render json: { result: 'success' }
    else
      flash.now[:notice] = "Nice try. You won't get rid of this awesome question."
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @course = Course.find(lesson.course.id)
    @enrollment = Enrollment.find_by(user: current_user, course: @course)
    @questions = Question.where(lesson: lesson)
  end

  def create
    @lesson = Lesson.find(params[:question][:lesson_id])
    @course = Course.find(@lesson.course.id)
    @question = Question.new(question_params)
    @questions = Question.where(lesson: @lesson)
    if @question.save
      flash[:notice] = "You just created a new question!"
      redirect_to course_lesson_path(@course, @lesson)
    else
      flash[:notice] = "Question couldn't be posted."
      render 'lessons/show'
    end
  end

  def new
    lesson
    @question = Question.new
  end

  def edit
    lesson
    @question = Question.find(params[:id])
  end

  def destroy
    lesson
    @course = lesson.course
    @question = Question.find(params[:id])
    @answers = @question.answers

    if @answers.destroy_all && @question.destroy
      flash[:notice] = "We got you. Your question will no longer be asked."
      redirect_to course_lesson_path(@course, lesson)
    else
      flash.now[:notice] = "Nice try. You won't get rid of this awesome question."
      render 'lessons/show'
    end
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:notice] = "Ask different! :p"
      redirect_to course_lesson_path(@question.lesson.course, @question.lesson)
    else
      flash.now[:notice] = "I say just keep it as is...or you can try to change again."
      render 'lessons/show'
    end
  end

  private

  def lesson
    @lesson ||= Lesson.find(params[:lesson_id])
  end

  def question_params
    params.require(:question).permit(
      :question,
      :lesson_id
    )
  end
end

app/views/questions/_form.html.haml
.container
  .row
    .col.s12
      = form_for @question do |f|
        .div.input-field
          = f.label :lesson_id
          = f.number_field :lesson_id, value: @lesson.id

        .div.input-field
          = f.label :question, 'Question'
          = f.text_field :question, autofocus: true

        .div.center
          %a.btn.waves-effect.waves-light
            %i.material-icons.left add
            = f.submit

app/views/questions/_lesson_overview.html.haml
%a.btn-floating.waves-effect.waves-light.teal#question-overview{ href: course_lesson_path(@course, @lesson) }
  %i.material-icons replay

app/views/questions/edit.html.haml
= render 'form'

app/views/questions/index.html.haml
- @questions.each do |question|
  %li= link_to question.question, question_path(question, lesson_id: @lesson.id)

app/views/questions/new.html.haml
= render 'form'