config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root 'courses#index'

  resources :users, only: [:show, :index]

  resources :courses do
    resources :lessons
  end

  resources :enrollments, only: [:new, :create, :index, :destroy, :show]

  resources :questions, only: [:index, :create, :new, :edit, :destroy, :update] do
    resources :answers
  end

  resources :texts, only: [:create]

  namespace :api do
    namespace :v1 do
      resources :questions, only: [:destroy]
      resources :enrollments, only: [:destroy]
      resources :lessons, only: [:update]
      resources :courses, only: [:index]
    end
  end
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  has_many :answers
  belongs_to :text

  validates :user, presence: true, uniqueness: { scope: :course }
  validates :course, presence: true, uniqueness: { scope: :user }
  validates :role, presence: true

  def learner?
    role == "learner"
  end

  def leader?
    role == "leader"
  end
end

app/controllers/api/v1/enrollments_controller.rb
class Api::V1::EnrollmentsController < Api::V1::BaseController
  def destroy
    @enrollment = Enrollment.find(params[:id])
    @course = @enrollment.course
    @answers = @enrollment.answers
    @answers.destroy_all
    if @enrollment.destroy
      flash[:notice] = "I'm sorry to hear that you removed #{@enrollment.user.first_name} from your class."
      render json: { result: 'success' }
    else
      flash[:notice] = "You couldn't remove #{@enrollment.user.first_name} from your class."
    end
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def show
    @course = Course.find(params[:course_id])
    @lessons = @course.lessons.sort_by { |a| a.lesson_no }
    @enrollment = Enrollment.find(params[:id])
    @learner = @enrollment.user
  end

  def new
    @course = Course.find(params[:course_id])
    @enrollment = Enrollment.new
  end

  def create
    @passcode = params[:passcode]
    @course = Course.find(params[:course_id])
    if @course.passcode == @passcode
      @enrollment = Enrollment.create(user: current_user, course: @course)
      flash[:notice] = "Welcome to #{@course.title}! You are now enrolled!"
      redirect_to course_path(@course)
    else
      flash.now[:notice] = "Nah...that's not the right passcode. Try again."
      render 'new'
    end
  end

  def index
    @course = Course.find(params[:course_id])
    @enrollments = Enrollment.where(course: @course)
    @leader = @enrollments.find_by(role: 'leader').user
    @lessons = @course.lessons
    @text = Text.new
    q_count = 0
    @lessons.each do |lesson|
      q_count += lesson.questions.size
    end
    @q_count = q_count
  end

  def destroy
    @course = Course.find(params[:course_id])
    @enrollment = Enrollment.find(params[:id])
    @answers = @enrollment.answers
    @answers.destroy_all
    if @enrollment.destroy
      flash[:notice] = "I'm sorry to hear that you removed #{@enrollment.user.first_name} from your class."
      redirect_to enrollments_path(course_id: @course.id)
    else
      flash[:notice] = "You couldn't remove #{@enrollment.user.first_name} from your class."
      render 'index'
    end
  end
end

app/views/enrollments/_passcode.html.haml
.container
  .row
    .col.s12
      = form_tag(enrollments_path(course_id: @course.id)) do
        = label_tag(:passcode)
        = text_field_tag(:passcode)
        = submit_tag("Join", class: "waves-effect secondary-content btn-large")

app/views/enrollments/index.html.haml
.div
  %h1.center= @course.title
  %h5.center Led by #{@leader.first_name} #{@leader.last_name}
.section
  .container
    %table.responsive-table.card-panel.hoverable.highlight.centered
      %thead
        %tr
          %th{ "data-field" => "id" } Name
          %th{ "data-field" => "questions" } Submissions
          %th{ "data-field" => "email" } Email
          - if @enrollments.present? && current_user == @leader
            %th{ "data-field" => "last_sign_in" } Last Signed In
            %th{ "data-field" => "remove" } Edit
            %th{ "data-field" => "message" } Text Message
      %tbody
        - if @enrollments.present? && current_user == @leader
          - @enrollments.each do |student|
            - if student.learner?
              %tr{ class: "enrollment-#{student.id}" }
                .h5
                  %td= link_to "#{student.user.first_name} #{student.user.last_name}", '#'
                %td= link_to "#{student.answers.size} / #{@q_count}" , enrollment_path(student, course_id: @course.id)
                %td= student.user.email
                %td= student.user.last_sign_in_at.localtime.strftime("%-I:%M %p %Z %-m/%-d/%-Y") unless student.user.last_sign_in_at.nil?
                %td
                  %a.btn-floating.waves-effect.waves-light.red.delete-enrollment{ href: enrollment_path(student, course_id: student.course), "data-method" => "delete" }
                    %i.material-icons.delete-enrollment remove
                %td
                  - if student.user.area_code == 510
                    / Modal Trigger
                    %a.modal-trigger{ :href => "#modal#{student.id}" }
                      %i.material-icons.medium.blue-text.text-lighten-1 chat
                    / Modal Structure
                    .modal{ id: "modal#{student.id}"}
                      .modal-content
                        = form_for @text do |f|
                          .div.input-field.hide
                            = f.label :enrollment_id
                            = f.number_field :enrollment_id, value: student.id
                          .div.input-field
                            = f.label :text
                            = f.text_field :text
                          %a.btn.waves-effect.waves-light.blue
                            = f.submit("Send")
                  - else
                    %i.material-icons.medium.grey-text.text-lighten-1 chat

        - elsif @enrollments.present? && @enrollments.find_by(user: current_user).learner?
          - @enrollments.each do |student|
            - unless student.user == current_user || student.user == @leader
              %tr
                %td #{student.user.first_name} #{student.user.last_name}
                %td= student.user.email
.section
  .container
    .row
      .col.s12.center-align
        = render 'lessons/course_overview'

app/views/enrollments/new.html.haml
= render 'passcode'

app/views/enrollments/show.html.haml
.container
  .row
    .col.s12.center
      %h1= @course.title
      %h3= @course.description
      %%br
      %h5 #{@learner.first_name} #{@learner.last_name}
      %%br
  .row
    - @lessons.each do |lesson|
      .row.card-panel
        .col.s6.left
          %h6 Lesson #{lesson.lesson_no}: #{lesson.title}
        .col.s6.right
          - if lesson.questions.present?
            - count = lesson.questions.length
            - lesson.questions.each do |question|
              - question.answers.each do |answer|
                - if answer.enrollment.user == @learner
                  %a.waves-light{ href: question_answer_path(question, answer) }
                    %i.material-icons.teal-text#complete star
                  - count -= 1
            - count.times do |icon|
              %i.material-icons.teal-text#incomplete star_border
  .row
    .col.s12.center
      = render 'lessons/course_overview'