config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root 'courses#index'

  resources :users, only: [:show, :index]

  resources :courses do
    resources :lessons
  end

  resources :enrollments, only: [:new, :create, :index, :destroy, :show]

  resources :questions, only: [:index, :create, :new, :edit, :destroy, :update] do
    resources :answers
  end

  resources :texts, only: [:create]

  namespace :api do
    namespace :v1 do
      resources :questions, only: [:destroy]
      resources :enrollments, only: [:destroy]
      resources :lessons, only: [:update]
      resources :courses, only: [:index]
    end
  end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :course
  has_many :questions

  validates :title, presence: true
  validates :content, presence: true
  validates :lesson_no, presence: true
end

app/controllers/api/v1/lessons_controller.rb
class Api::V1::LessonsController < Api::V1::BaseController

  def update
    @lesson = Lesson.find(params[:id])
    @course = @lesson.course
    @enrollment = Enrollment.find_by(role: "leader", course: @course)
    @lessons = Lesson.where(course_id: @course).sort_by { |a| a.lesson_no }

    if params[:direction].present? && params[:direction] == "down"
      @next_lesson = Lesson.find_by(lesson_no: @lesson.lesson_no + 1, course: @course)
      if @next_lesson.present?
        @next_lesson.increment!(:lesson_no, -1)
        @lesson.increment!(:lesson_no)
      end
      @lessons = Lesson.where(course_id: @course).sort_by { |a| a.lesson_no }
      render json: { html: render_to_string(partial: 'courses/lessons', layout: false, locals: { lessons: @lessons }) }

    elsif params[:direction].present? && params[:direction] == "up"
      @previous_lesson = Lesson.find_by(lesson_no: @lesson.lesson_no - 1, course: @course)
      if @previous_lesson.present?
        @previous_lesson.increment!(:lesson_no)
        @lesson.increment!(:lesson_no, -1)
      end
      @lessons = Lesson.where(course_id: @course).sort_by { |a| a.lesson_no }
      render json: { html: render_to_string(partial: 'courses/lessons', layout: false, locals: { lessons: @lessons }) }
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!

  def show
    @lesson = Lesson.find(params[:id])
    @course = @lesson.course
    @enrollment = Enrollment.find_by(user: current_user, course: @course)
    @questions =  Question.where(lesson: @lesson)
    @lessons = Lesson.where(course_id: @course).sort_by { |a| a.lesson_no }
    if @enrollment.nil?
      redirect_to new_enrollment_path(course_id: @course.id)
    end
  end

  def create
    @course = Course.find(params[:course_id])
    @lesson = Lesson.new(lesson_params)
    @lesson.course = @course
    @lesson_no = @course.lessons.length + 1
    if @lesson.save
      flash[:notice] = " Woohoo! You've just added a lesson."
      redirect_to course_lesson_path(@course, @lesson)
    else
      flash.now[:error] = "Ooops...Something is not right."
      flash.now[:notice] = @course.errors.full_messages
      render 'edit'
    end
  end

  def new
    @course = Course.find(params[:course_id])
    @lesson = Lesson.new
    @enrollment = Enrollment.find_by(user: current_user, course: @course)
    @lesson_no = @course.lessons.length + 1
  end

  def destroy
    @course = Course.find(params[:course_id])
    @lesson = Lesson.find(params[:id])
    @questions = Question.where(lesson: @lesson)
    if @questions.present?
      @questions.each do |question|
        question.answers.destroy_all
      end
      @questions.destroy_all
    end
    if @lesson.destroy
      flash[:notice] = "Buddy, I hope you have a better lesson in mind,
      cuz you just deleted one heck of a lesson."
      redirect_to course_path(@course)
    else
      flash.now[:notice] = "Hey, you can't delete this stuff.
      Who are you trying to trick?"
      render :show
    end
  end

  def edit
    @course = Course.find(params[:course_id])
    @lesson = Lesson.find(params[:id])
    @enrollment = Enrollment.find_by(user: current_user, course: @course)
    @lesson_no = @lesson.lesson_no
    if !@enrollment.nil? && @enrollment.leader?
      render 'edit'
    else
      redirect_to course_lesson_path(@course, @lesson)
    end
  end

  def update
    @course = Course.find(params[:course_id])
    @lesson = Lesson.find(params[:id])
    @enrollment = Enrollment.find_by(user: current_user, course: @course)
    if params[:direction].present? && params[:direction] == "down"
      @next_lesson = Lesson.find_by(course: @course, lesson_no: @lesson.lesson_no + 1)

      if @next_lesson.present?
        @lesson.increment!(:lesson_no)
        @next_lesson.increment!(:lesson_no, -1)
        flash[:notice] = "#{current_user.first_name},
        you want that lesson to be later, eh? Good thinking."
        redirect_to course_path(@course)
      else
        @lessons = Lesson.where(course_id: @course).sort_by { |a| a.lesson_no }
        render 'courses/show'
      end
    elsif params[:direction].present? && params[:direction] == "up"
      @previous_lesson = Lesson.find_by(course: @course, lesson_no: @lesson.lesson_no - 1)
      if @previous_lesson.present?
        if @previous_lesson.increment!(:lesson_no)
          @lesson.increment!(:lesson_no, -1)
          flash[:notice] = "#{current_user.first_name},
          you want that lesson to be sooner, eh? Wise choice."
          redirect_to course_path(@course)
        end
      else
        @lessons = Lesson.where(course_id: @course).sort_by { |a| a.lesson_no }
        render 'courses/show'
      end
    end

    unless params[:lesson].nil? || params[:lesson].empty?
      if @lesson.update(lesson_params)
        flash[:notice] = "#{current_user.first_name},
        did you just make your lesson even better? Sweet!"
        redirect_to course_lesson_path(@course, @lesson)
      else
        flash.now[:notice] = "Sorry buddy, we couldn't change your lesson.
        Your input is invalid."
        render 'edit'
      end
    end
  end

  private

  def lesson_params
    params.require(:lesson).permit(
      :title,
      :content,
      :lesson_no,
      :course_id
    ).merge(course: Course.find(params[:course_id]))
  end
end

app/views/lessons/_course_overview.html.haml
%a.btn-floating.waves-effect.waves-light.teal#course-overview{ href: course_path(@course) }
  %i.material-icons replay

app/views/lessons/_form.html.haml
= form_for [@course, @lesson] do |f|
  .div.input-field
    = f.label :lesson_no
    = f.number_field :lesson_no, value: @lesson_no

  .div.input-field
    = f.label :title
    = f.text_field :title

  .div
    = f.label :content
    = f.text_area :content, class: "tinymce", rows: 40, cols: 120


  .div.center
    .waves-effect.secondary-content.btn-large.center
      = f.submit

app/views/lessons/_lesson.html.haml
= form_for [@course, @lesson] do |f|
  .div
    = f.label :lesson_no
    = f.number_field :lesson_no, value: @lesson_no
  .div
    = f.label :title
    = f.text_field :title

  .div
    = f.label :content
    = f.text_area :content, id: 'froala-editor'

  .div
    = f.submit

app/views/lessons/edit.html.haml
.container
  = render 'form'

app/views/lessons/new.html.haml
.container
  - if !@enrollment.nil? && @enrollment.leader?
    = render 'form'

app/views/lessons/show.html.haml
.container
  %ul.collapsible{ "data-collapsible" => "accordion" }
    %li
      .collapsible-header
        %h3.center #{@lesson.lesson_no}. #{@lesson.title}
        = @lesson.content.html_safe
      - if @enrollment.leader?
        .collapsible-body
          .row
            .col.s12.center
              %%br
              %a.btn.waves-effect.waves-light.blue-grey.darken-3#edit-lesson{ href: edit_course_lesson_path(@course, @lesson) }
                %i.material-icons mode_edit
              %a.btn.waves-effect.waves-light.red#delete-lesson{ href: course_lesson_path(@course, @lesson), "data-method" => "delete" }
                %i.material-icons remove
    .section
      .container
        .row.center
          .col.s12
            %h5 Questions
            %ul.collapsible{ "data-collapsible" => "accordion" }
              - @questions.each do |question|
                %li.card-panel.hoverable{ class: "question-#{question.id}" }
                  - if @enrollment.leader?
                    .collapsible-header
                      %h5= link_to question.question, question_answers_path(question)
                    .collapsible-body
                      %a.btn.waves-effect.waves-light.blue-grey.darken-3.edit-question{ href: edit_question_path(question, lesson_id: @lesson.id) }
                        %i.material-icons edit
                      %a.btn.waves-effect.waves-light.red.delete-question{ href: question_path(question, lesson_id: @lesson.id), "data-method" => "delete" }
                        %i.material-icons.delete-question remove
                  - elsif @enrollment.learner?
                    .collapsible-header
                      - user_answer = question.answers.find_by(enrollment: @enrollment)
                      - if user_answer.present? && user_answer.enrollment.user == current_user
                        = link_to question.question, new_question_answer_path(question)
                        %i.material-icons.teal-text check_box
                      - else
                        = link_to question.question, new_question_answer_path(question)
                        %i.material-icons.teal-text check_box_outline_blank
            - if @enrollment.leader?
              %a.btn-large.col.s12.waves-effect.waves-light.teal.add-question{ href: new_question_path(lesson_id: @lesson.id) }
                %i.material-icons.teal add
    .section
      .container
        .row.center
          = render 'course_overview'